# Generated by Django 3.1.5 on 2021-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210226_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/products'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(upload_to='static/images/products'),
        ),
    ]
